[theme]
primaryColor = "#ff6411"  # Laranja VRZ
secondaryColor = "#0018b4"  # Azul VRZ
backgroundColor = "#ffffff"  # Cinza claro
secondaryBackgroundColor = "#ffffff"  # Branco
textColor = "#000000"  # Preto
font = "MONTSERRAT FAMILY"